title: Joel Elford
logo: "/images/LIprofileBW.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent master’s graduate in mathematics with a passion for discovering valuable insights from data through the use of novel techniques. A proven versatile learner with a strong aptitude for problem solving who is keen to apply the latest methods on difficult problems. Experience with modelling, machine learning, visualization and team collaboration. 
  <br><br>
  <a href="https://github.com/joelford/joelford.github.io/blob/master/joel_elford_resume.md">Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/joel-elford-811751122">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
