title: Joel Elford
logo: "/images/LIprofileBW.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent master’s graduate in mathematics with a passion for discovering valuable insights from data through the use of novel techniques.
  <br><br>
  <a href="https://github.com/joelford/joelford.github.io/blob/master/joel_elford_resume.md">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/joel-elford-811751122">Visit My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
