title: Joel Elford
logo: "/images/LIprofileBW.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/joel-elford-811751122/>LinkedIn</a> 
  
theme: jekyll-theme-slate
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
